
name: Ubuntu Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'client/bbs.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'SimpleDiary-ubuntu'
          options: --onefile, --name "SimpleDiary", --console, 
      - uses: actions/upload-artifact@v3
        with:
          name: SimpleDiary-ubuntu
          path: dist
  
